name: bcbp
description: "Encoding/decoding library for the IATA Bar Coded Boarding Pass"
version: 1.0.0
homepage:

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
