name: bcbp
description: "Encoding/decoding library for the IATA Bar Coded Boarding Pass"
version: 0.0.3
homepage: https://github.com/phucanh08/bcbp
repository: https://github.com/phucanh08/bcbp

environment:
  sdk: ">=2.16.0 <4.0.0"
